### ISSUE TITLE
Make REST API endpoints only accessible by sysadmins

### ISSUE THREAD

**Issue by pathob** [aservo/confluence-confapi-plugin#2]
The preferred way to do that would be to use a ResourceFilter. But I had problems injecting the necessary components into that filter.

```java
@ResourceFilters(SysadminOnlyResourceFilter.class)
```

**Comment by lehmannk** [comment]
das hat damit zu tun, dass Atlassian hier wiedermal für jede App eine eigene Impl geschaffen hat. Die Default Impl, die du mit SysadminOnlyResourceFilter.class reingezogen hast, funkitoniert wahrscheinlich bei deiner Beispiel App nicht. Ich habe mal versuchsweise für Confluence eine eigen Implementierung gebaut: 

```
 public ContainerRequest filter(ContainerRequest containerRequest) {
        User loggedInUser = AuthenticatedUserThreadLocal.get();
        if (loggedInUser == null) {
            throw new AuthenticationRequiredException();
        } else if (!permissionManager.isConfluenceAdministrator(loggedInUser)) {
            throw new AuthorisationException("Client must be authenticated as an administrator to access this resource.");
        }
        return containerRequest;
    }
```

und dann die Annotations an die Resource Klassen gehängt. Damit geht es. Die Annotation ist meiner Meinung nach mehr straightforward als der implizite Methodenaufruf pro Resource method.
